

import Navbar from './navbarpage/Navbar'
import '../index.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>

          <Navbar></Navbar>
          {children}
      </body>
    </html>
  )
}
