

import Navbar from './navbarpage/Navbar'
import '../index.css'
import ClientProvider from "./ClientProvider"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ClientProvider>

          <Navbar></Navbar>
          {children}
        </ClientProvider>
      </body>
    </html>
  )
}
